FROM elasticsearch:8.12.2

# USER root
# WORKDIR /app
# RUN apt-get update && apt install -y wget gnupg2
# COPY ./gcs.sh /app
# RUN sh ./gcs.sh
# RUN chown www-data:www-data /usr/share/elasticsearch/data
# COPY ./gcfuse.sh /app
# COPY ./supervisor.conf /etc/supervisor/conf.d/supervisor.conf
# USER elasticsearch